# Generated by Django 5.2 on 2025-06-09 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='estado',
            field=models.CharField(choices=[('PEND', 'Pendiente'), ('ENV', 'Enviado'), ('ENT', 'Entregado'), ('CAN', 'Cancelado')], default='PEND', max_length=5),
        ),
    ]
