# Generated by Django 5.2 on 2025-08-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_compra_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcarrito',
            name='steam_appid',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
