# Generated by Django 5.2 on 2025-08-11 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_itemcarrito_steam_appid'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcarrito',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
