# Generated by Django 5.2 on 2025-08-11 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0003_alter_juego_genero'),
        ('tienda', '0004_itemcarrito_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcarrito',
            name='cantidad',
        ),
        migrations.AlterField(
            model_name='itemcarrito',
            name='juego',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='juegos.juego'),
        ),
    ]
