# Generated by Django 5.2 on 2025-08-14 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0003_alter_juego_genero'),
        ('tienda', '0005_remove_itemcarrito_cantidad_alter_itemcarrito_juego'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecompra',
            name='juego',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='juegos.juego'),
        ),
        migrations.CreateModel(
            name='DetalleCompraSteam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steam_appid', models.PositiveIntegerField()),
                ('nombre', models.CharField(max_length=200)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.compra')),
            ],
        ),
    ]
