# Generated by Django 5.2 on 2025-05-02 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.URLField()),
                ('descripcion', models.TextField()),
                ('fecha_lanzamiento', models.DateField()),
                ('desarrollador', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=50)),
                ('descuento', models.IntegerField()),
                ('es_gratis', models.BooleanField(default=False)),
            ],
        ),
    ]
