# Generated by Django 5.2 on 2025-05-08 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juego',
            name='appid',
        ),
        migrations.RemoveField(
            model_name='juego',
            name='es_gratis',
        ),
        migrations.RemoveField(
            model_name='juego',
            name='imagen',
        ),
        migrations.AddField(
            model_name='juego',
            name='imagen2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='juego',
            name='imagen3',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='juego',
            name='imagen4',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='juego',
            name='imagen5',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='juego',
            name='imagen_miniatura',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='juego',
            name='imagen_principal',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='juego',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
