# Generated by Django 5.2 on 2025-06-10 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0002_remove_juego_appid_remove_juego_es_gratis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='genero',
            field=models.CharField(choices=[('Acción', 'Acción'), ('Aventura', 'Aventura'), ('Casual', 'Casual'), ('Experimental', 'Experimental'), ('Puzles', 'Puzles (Rompecabezas)'), ('Carreras', 'Carreras'), ('RPG', 'RPG (Rol)'), ('Simulación', 'Simulación'), ('Deportes', 'Deportes'), ('Estrategia', 'Estrategia'), ('Mesa', 'Juegos de mesa')], max_length=50),
        ),
    ]
